name: Run Masoud EXE with Detailed Logs

on:
  workflow_dispatch:

jobs:
  run-masoud:
    runs-on: windows-latest
    timeout-minutes: 300

    steps:
      - name: Prepare log folder
        shell: powershell
        run: |
          New-Item -Path C:\app -ItemType Directory -Force | Out-Null
          New-Item -Path C:\app\logs -ItemType Directory -Force | Out-Null
          Write-Host "[OK] Prepared C:\app and C:\app\logs"

      - name: Add Windows Defender exclusions (BEFORE download)
        shell: powershell
        run: |
          Write-Host "[*] Configuring Windows Defender exclusions..."
          try {
            Add-MpPreference -ExclusionPath "C:\app" -ErrorAction Stop
            Write-Host "[OK] Added folder exclusion: C:\app"
            
            Add-MpPreference -ExclusionProcess "masoud.exe" -ErrorAction Stop
            Write-Host "[OK] Added process exclusion: masoud.exe"
            
            Write-Host "[OK] All Defender exclusions configured successfully"
          } catch {
            Write-Host "[!] Warning: Could not add exclusions: $($_.Exception.Message)"
            Write-Host "[!] Continuing anyway... (might face blocking issues)"
          }

      - name: Download ZIP with retries
        shell: powershell
        run: |
          $url = 'https://github.com/masezahedi/MasoudApp/raw/main/Masoud-6.24.0-windows-x64.zip'
          $out = 'C:\app\app.zip'
          $maxAttempts = 3
          $attempt = 0
          $success = $false

          while ($attempt -lt $maxAttempts -and -not $success) {
            $attempt++
            Write-Host "[*] Download attempt $attempt/$maxAttempts..."
            try {
              Invoke-WebRequest -Uri $url -OutFile $out -UseBasicParsing -ErrorAction Stop
              if (Test-Path $out) {
                $size = (Get-Item $out).Length
                $sizeMB = [math]::Round($size/1MB, 2)
                Write-Host "[OK] Downloaded successfully - Size: $sizeMB MB"
                if ($size -gt 0) {
                  $success = $true
                } else {
                  Write-Host "[ERR] File size is 0 bytes"
                }
              } else {
                Write-Host "[ERR] File not found after download"
              }
            } catch {
              Write-Host "[ERR] Attempt $attempt failed: $($_.Exception.Message)"
            }
            if (-not $success -and $attempt -lt $maxAttempts) { 
              Write-Host "[*] Waiting 5 seconds before retry..."
              Start-Sleep -Seconds 5 
            }
          }

          if (-not $success) {
            Write-Host "[ERR] ALL DOWNLOAD ATTEMPTS FAILED"
            exit 1
          }

      - name: Extract ZIP
        shell: powershell
        run: |
          $in = 'C:\app\app.zip'
          $dest = 'C:\app'

          if (-not (Test-Path $in)) {
            Write-Host "[ERR] ZIP file not found: $in"
            exit 1
          }

          Write-Host "[*] Extracting $in to $dest..."
          Write-Host "[*] ZIP file info:"
          Get-Item $in | Select-Object Name, Length, LastWriteTime | Format-Table
          
          try {
            Write-Host "[*] Using Expand-Archive to extract ZIP..."
            Expand-Archive -Path $in -DestinationPath $dest -Force -ErrorAction Stop
            Write-Host "[OK] Extraction completed successfully"
            
            $items = @(Get-ChildItem $dest -Recurse -ErrorAction SilentlyContinue)
            Write-Host "[OK] Total items after extraction: $($items.Count)"
            Write-Host "[*] Directory contents:"
            Get-ChildItem $dest -Depth 1 | Format-Table Name, Length
          } catch {
            Write-Host "[ERR] Exception during extraction: $($_.Exception.Message)"
            exit 1
          }

      - name: Find masoud.exe
        shell: powershell
        id: findexe
        run: |
          Write-Host "[*] Searching for masoud.exe..."
          $exe = Get-ChildItem -Path C:\app -Recurse -Filter "masoud.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
          
          if (-not $exe) {
            Write-Host "[ERR] masoud.exe not found!"
            exit 1
          }
          
          $path = $exe.FullName
          Write-Host "[OK] Found masoud.exe at: $path"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "exePath=$path"

      - name: Run masoud.exe
        shell: powershell
        run: |
          $exePath = '${{ steps.findexe.outputs.exePath }}'
          
          if (-not (Test-Path $exePath)) {
            Write-Host "[ERR] Executable not found at: $exePath"
            exit 1
          }
          
          Write-Host "[*] Running masoud.exe..."
          Write-Host "[*] Path: $exePath"
          try {
            & $exePath *> C:\app\masoud_output.log
            $exit = $LASTEXITCODE
            
            if ($exit -eq 0) {
              Write-Host "[OK] Program executed successfully (exit code: 0)"
            } else {
              Write-Host "[!] Program finished with exit code: $exit"
            }
            
            Write-Host ""
            Write-Host "[*] Program output (first 100 lines):"
            Write-Host "======================================"
            Get-Content C:\app\masoud_output.log -TotalCount 100
            Write-Host "======================================"
            
          } catch {
            Write-Host "[ERR] Exception while running program: $($_.Exception.Message)"
            exit 1
          }

      - name: Summary
        shell: powershell
        if: always()
        run: |
          Write-Host ""
          Write-Host "======================================"
          Write-Host "        EXECUTION SUMMARY"
          Write-Host "======================================"
          Write-Host ""
          
          $items = @(Get-ChildItem C:\app -Recurse -ErrorAction SilentlyContinue)
          Write-Host "[*] Total files in C:\app: $($items.Count)"
          
          if (Test-Path C:\app\masoud_output.log) {
            $outputSize = (Get-Item C:\app\masoud_output.log).Length
            $outputSizeKB = [math]::Round($outputSize/1KB, 2)
            Write-Host "[*] Program output file size: $outputSizeKB KB"
          }
          
          Write-Host ""
          Write-Host "[*] Log files created:"
          Get-ChildItem C:\app\logs -ErrorAction SilentlyContinue | ForEach-Object {
            Write-Host "    - $($_.Name)"
          }
          
          Write-Host ""
          Write-Host "[OK] Workflow completed"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: masoud-artifacts
          path: |
            C:\app\masoud_output.log
            C:\app\Masoud-6.24.0-windows-x64
